# Task : Session 1
Solve these questions own your own and try to test yourself what you have learned in the session.

Happy Learning!

### Q1 :- Print the given strings as per stated format.

**Given strings**: 
```
"Data" "Science" "Mentorship" "Program" 
"By" "CampusX"
```
**Output**: 
``` 
Data-Science-Mentorship-Program-started-By-CampusX
```

Concept- [Seperator and End]

In [ ]:
# Write your code here
print("Data","Science","Mentorship","Program",sep='-',end='-started-')
print("By","CampusX",sep='-')

Data-Science-Mentorship-Program-started-By-CampusX

### Q2:- Write a program that will convert celsius value to fahrenheit.

In [ ]:
# Write your code here
def celfaren(celcius):
    
    faren = celcius*(9/5)+32
    print("Fahrenheit",faren)

celcius = float(input("Enter the temperature in Celcius "))
celfaren(celcius)

Enter the temperature in Celcius 0
Fahrenheit 32.0

### Q3:- Take 2 numbers as input from the user.Write a program to swap the numbers without using any special python syntax.

In [ ]:
# Write your code here

a = input("Enter 1st number: ")
b = input("Enter 2nd number: ")

temp = a
a = b
b = temp

print(a,b)

Enter 1st number: 12
Enter 2nd number: 33
33 12

### Q4:- Write a program to find the euclidean distance between two coordinates.Take both the coordinates from the user as input.

In [ ]:
# Write your code here

a1=int(input("ENter x cor of 1st point:"))
b1=int(input("ENter y cor of 1st point:"))
x1=int(input("ENter x cor of 2nd point:"))
y1=int(input("ENter y cor of 2nd point:"))

dist = ((x1-a1)**2 + (y1-b1)**2)**0.5

print(round(dist,2))

ENter x cor of 1st point:14
ENter y cor of 1st point:12
ENter x cor of 2nd point:10
ENter y cor of 2nd point:8
5.66

### Q5:- Write a program to find the simple interest when the value of principle,rate of interest and time period is provided by the user.

In [ ]:
# Write your code here

principle = int(input("Enter principle amount:"))
interest = float(input("Enter interest RAte:"))
time = float(input("Enter time amount:"))

si = (principle*interest*time)/100

print(round(si,2))

Enter principle amount:122
Enter interest RAte:33
Enter time amount:4
161.04

### Q6:- Write a program that will tell the number of dogs and chicken are there when the user will provide the value of total heads and legs.

For example:
Input:
heads -> 4
legs -> 12
<br>
Output:
dogs -> 2
chicken -> 2

In [ ]:
# Write your code here

head = int(input("Enter number of heads:"))
legs = int(input("Enter number of legs:"))


if (head>0 or legs>0) and 4*head>=legs:

    c = int((4*head - legs)/2)
    d = int(head-c)
    #print (d,c)
    print("no of dogs",d)
    print("no of chic",c)
   
else:
    print("Invalid input")

Enter number of heads:1
Enter number of legs:4
no of dogs 1
no of chic 0

### Q7:- Write a program to find the sum of squares of first n natural numbers where n will be provided by the user.

In [ ]:
# Write your code here

n = int(input("Enter N:"))
sum = 0
for i in range(1,n+1):
    sum = sum+(i*i)

print(sum)

Enter N:3
14

### Q8:- Given the first 2 terms of an Arithmetic Series.Find the Nth term of the series. Assume all inputs are provided by the user.

In [ ]:
# Write your code here
# n = a+(n-1)d
first = int(input("Enter 1st term: "))
second = int(input("Enter 2nd term: "))

n = int(input("which term you want to find:"))

cd = second - first
nth_term = first+(n-1)*cd

print("{}rd_term: {}".format(n,nth_term))

Enter 1st term: 40
Enter 2nd term: 80
which term you want to find:3
3rd_term: 120

### Q9:- Given 2 fractions, find the sum of those 2 fractions.Take the numerator and denominator values of the fractions from the user.

In [9]:
# Write your code here

from fractions import Fraction
n1 = int(input())
d1 = int(input())
n2 = int(input())
d2 = int(input())

num = n1*d2 + n2*d1
denom = (d1*d2)


print("{}/{}".format(num,denom))

3
7
11
17
128/119

 3### Q10:- Given the height, width and breadth of a milk tank, you have to find out how many glasses of milk can be obtained? Assume all the inputs are provided by the user.



Input:<br>
Dimensions of the milk tank<br>
H = 20cm, L = 20cm, B = 20cm
<br><br>
Dimensions of the glass<br>
h = 3cm, r = 1cm

In [13]:
# Write your code here

import math
h_t = float(input("Height"))
b_t = float(input("Breadth"))
l_t = float(input("Lenght"))

h_g = float(input("Height"))
r_g = float(input("radius"))

v_t = h_t*b_t*l_t
v_g = 3.14*r_g*r_g*h_g

no_of_glasses = print("No of glasses:",math.floor(v_t/v_g))

Height12
Breadth12
Lenght12
Height2
radius3
No of glasses: 30